### ISSUE TITLE
Tau Battlesuit Bug

### ISSUE THREAD

**Issue by Venom9305** [OnlineCodex/OnlineCodex#212]
Hello
Thres a bug for every Tau Battlesuit unit. Every unit has automatic the maximum number of modells and you cant reduce them in choice.

Thanks for fixing :)

**Comment by chisui** [comment]
@Venom9305 I could not reproduce with the current `1.13.1` release. Please make sure that you are using the current release, since it's the only one we provide bugfixes for. If the issue still persists share your Operation System name and Version (like Win10/7, MacOs, Linux(KDE)), Java version and the exact actions you took after launching the app.
